prefix=${CMAKE_INSTALL_PREFIX}
libdir=${CMAKE_INSTALL_FULL_LIBDIR}
includedir=${CMAKE_INSTALL_FULL_INCLUDEDIR}
minimal="-lucommon ${PACKAGE_LIBS}"

Name: ${PROJECT_NAME}
Description: ${PROJECT_NAME} library
Version: ${PACKAGE_FILE_VERSION}
Libs: -lusecure -lucommon ${ADDITIONAL_LIBS} ${PACKAGE_LIBS} -L${CMAKE_INSTALL_FULL_LIBDIR}
Cflags: ${PACKAGE_FLAGS} -I${CMAKE_INSTALL_FULL_INCLUDEDIR}

